name: hand2hand
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  input_quantity: ^2.5.0
  geolocator: ^14.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  #Database
  supabase_flutter: ^2.8.4
  timeago: ^3.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png

